version: '3'

services:
  app:
    image: project_e
    container_name: project_e_app
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      - mongo
    volumes:
      - /home/sergey/projects/project_e/server:/usr/src/app/server
      - /home/sergey/projects/project_e/client:/usr/src/app/client
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27018:27017'